### PR TITLE
Dynamically set browser page titles

### PR DESCRIPTION
**Pull request by dfmcphee**
This fixes https://github.com/CovidShield/portal/issues/13.

It will now dynamically change the page title based on route

### CODE REVIEW

**Comment by svinkle** [comment]
@dfmcphee Add/edit/settings view doesn't seem to update. Also, I'd recommend keeping the app name in the `title` for consistency.

Eg., `Settings | COVID Shield`

**Comment by dfmcphee** [comment]
Good call. Updated with your suggestion and fixed the add/edit ones. 👍

**Comment by svinkle** [comment]
Minor thing: the Settings page outputs "Edit user." I know it's the same form but I feel like it should be consistent with the `h1`.

**Comment by dfmcphee** [comment]
> Minor thing: the Settings page outputs "Edit user." I know it's the same form but I feel like it should be consistent with the `h1`/menu link.

 Makes sense. Updated to do that. 👍

**Pull request merged**
